(in-package :lispmud)

(defclass zone ()
  ((room-list :initarg :roomlist :initform nil :accessor room-list)
   (exit-hash :initarg :exithash :initform (make-hash-table :test 'equal) :accessor exit-hash)
   (description :initarg :description :accessor description)))

(defun load-zone (file-name)
  (with-open-file (stream file-name)
    (let ((zone (make-instance 'zone :description (read stream))))
      (with-slots (room-list exit-hash) zone
	(let ((room-id-hash (make-hash-table :test 'equal)))
	  (dolist (room-plist (read stream))
	    (let ((cur-room  (make-instance 'room1 :description (getf room-plist :description))))
	      (push cur-room room-list)
	      (setf (gethash (getf room-plist :id) room-id-hash) cur-room); (getf room-plist :id)) 
	      (dolist (i '(:south :north :west :east))
		(setf (gethash (cons cur-room i) exit-hash) (getf room-plist i)))))
	  (maphash #'(lambda (key val)
		       (setf (gethash key exit-hash) (gethash val room-id-hash)))
		   exit-hash)
					;(print exit-hash)
	  (maphash #'(lambda (key val)
		       (format t "~a ~a~%" key val))
		   exit-hash)
	  (format t "rooms: ~a~%" room-list)
	  (format t "descr: ~a~%" (description (first room-list)))
	  zone)))))
